### ISSUE TITLE
Fetch only metadata not creating JSON file

### ISSUE THREAD

**Issue by Scoutski** [rarcega/instagram-scraper#165]
Hey there,

I'm hoping this is a usage issue, but as per the readme and this previous ticket: https://github.com/rarcega/instagram-scraper/issues/58

I'm trying to scrape an account but only get the metadata. I can confirm that metadata comes through when I don't specify a media type (or provide a valid one), but when trying to specify none, the JSON does not get created/updated and it doesn't seem there is anyway to get the data without downloading all the files. If I can provide anymore details, let me know.

**Comment by safc** [comment]
It seems like a bug with the latest release. If you use the December '17 release (v1.5.18) the issue should be resolved.

**Comment by VasiliPupkin256** [comment]
Probably [this commit](http://github.com/rarcega/instagram-scraper/commit/94654f6a98abf2a5b8bedb97e6bbf0baa544711a) and [this line](http://github.com/rarcega/instagram-scraper/blob/94654f6a98abf2a5b8bedb97e6bbf0baa544711a/instagram_scraper/app.py#L505) changed the behavior. If you decide to download no video nor images then no metadata associated with the media will be downloaded. Also the version 1.5.18 didn't download metadata if run with `--media-types story`

**Comment by tomasjanu** [comment]
It seams to me that this issue still does not work. This code "instagram-scraper lewishamilton --media-types none --media-metadata" simply does not download anything. 

What am I doing wrong?
